<div style="position: absolute; right: 0; top:50px;display: flex;flex-direction: column">
    <?php foreach ($block->getBanners() as $img):  ?>
        <img src="<?=$img?>" style="max-width: 200px"/>
    <?php endforeach; ?>
</div>
<div style="position: absolute; left: 0; top:50px;display: flex;flex-direction: column">
    <?php foreach ($block->getBanners() as $img):  ?>
        <img src="<?=$img?>" style="max-width: 200px"/>
    <?php endforeach; ?>
</div>
